ENTITY_RESPONSE = {
    "id": 149,
    "name": "INTERMEDIADORA DE NEGOCIOS LTDA",
    "entities_id": 0,
    "completename": "GNEW > INTERMEDIADORA DE NEGOCIOS LTDA",
    "comment": "",
    "level": 2,
    "sons_cache": None,
    "ancestors_cache": "[\"0\"]",
    "address": None,
    "postcode": None,
    "town": None,
    "state": None,
    "country": None,
    "website": None,
    "phonenumber": None,
    "fax": None,
    "email": None,
    "admin_email": None,
    "admin_email_name": None,
    "admin_reply": None,
    "admin_reply_name": None,
    "notification_subject_tag": None,
    "ldap_dn": None,
    "tag": 28247127000129,
    "authldaps_id": 0,
    "mail_domain": None,
    "entity_ldapfilter": None,
    "mailing_signature": None,
    "cartridges_alert_repeat": -2,
    "consumables_alert_repeat": -2,
    "use_licenses_alert": -2,
    "send_licenses_alert_before_delay": -2,
    "use_certificates_alert": -2,
    "send_certificates_alert_before_delay": -2,
    "use_contracts_alert": -2,
    "send_contracts_alert_before_delay": -2,
    "use_infocoms_alert": -2,
    "send_infocoms_alert_before_delay": -2,
    "use_reservations_alert": -2,
    "autoclose_delay": -2,
    "notclosed_delay": -2,
    "calendars_id": -2,
    "auto_assign_mode": -2,
    "tickettype": -2,
    "max_closedate": "2021-06-08 15:37:52",
    "inquest_config": -2,
    "inquest_rate": 0,
    "inquest_delay": -10,
    "inquest_URL": None,
    "autofill_warranty_date": -2,
    "autofill_use_date": -2,
    "autofill_buy_date": -2,
    "autofill_delivery_date": -2,
    "autofill_order_date": -2,
    "tickettemplates_id": -2,
    "entities_id_software": -2,
    "default_contract_alert": -2,
    "default_infocom_alert": -2,
    "default_cartridges_alarm_threshold": -2,
    "default_consumables_alarm_threshold": -2,
    "delay_send_emails": -2,
    "is_notif_enable_default": -2,
    "inquest_duration": 0,
    "date_mod": "2024-08-22 14:35:04",
    "date_creation": "2021-06-08 15:37:52",
    "autofill_decommission_date": -2,
    "links": [
        {
            "rel": "Entity",
            "href": "https://glpi-teste.com.br/apirest.php/Entity/0"
        },
        {
            "rel": "Calendar",
            "href": "https://glpi-teste.com.br/apirest.php/Calendar/-2"
        },
        {
            "rel": "TicketTemplate",
            "href": "https://glpi-teste.com.br/apirest.php/TicketTemplate/-2"
        },
        {
            "rel": "Entity",
            "href": "https://glpi-teste.com.br/apirest.php/Entity/-2"
        },
        {
            "rel": "Document_Item",
            "href": "https://glpi-teste.com.br/apirest.php/Entity/149/Document_Item/"
        }
    ]
}